name: Publish MkDocs

on: # would it make sense to trigger the CI pipeline also when creating a new branch?
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Mkdocs to gh-pages branch
    runs-on: ubuntu-latest

    steps:
      - name: Get repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install Python dependencies
        run: pip install -r mkdocs_requirements.txt

      - name: Copy notebooks into docs
        run: cp -r notebooks/* docs/ | echo "No notebooks found"

      - name: Deploy Mkdocs
        run: mkdocs gh-deploy --force
